# -*- coding: utf-8 -*-
"""hw1_binary_hex_converter

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d380pYQwHrlkgqsVQ1Uu3vT0iHtxCJlU
"""

i = int(input('請輸入0～225之間的數:'))
number = 7
a = 0
stbytef = 0
stbytes = 0
list = [0,0,0,0,0,0,0,0]
ascllf = 65
asclls = 65

if i ==0:
  print('\n2進位為: 0')
else:
  print("\n2進位為: ",end = "")
while True:
    if i - 2**number >= 0 :
        print("1",end = "")
        list[7 - number] = 1
        a += 1
        i -= 2**number
        number -= 1
    elif i - 2**number < 0 and a != 0:
        print("0",end = "")
        list[7 - number] = 0
        number -= 1
    elif i - 2**number < 0 and a == 0:
        list[7 - number] = 0
        number -= 1

    if number < 0:
        print("\n16進位為: ",end="")
        stbytef = list[0]*(2**3) + list[1]*(2**2) + list[2]*(2**1)+ list[3]*(2**0)
        if stbytef <= 9 and stbytef > 0:
            print(stbytef,end = "")
        if stbytef > 9:
            ascllf += stbytef - 10
            print(chr(ascllf),end = "")

        stbytes = list[4]*(2**3) + list[5]*(2**2) + list[6]*(2**1) + list[7]*(2**0)
        if stbytes <= 9:
            print(stbytes)
        if stbytes > 9:
            asclls += stbytes - 10
            print(chr(asclls),end = "")

        break